include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    avoid_print: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    use_super_parameters: warning
    sized_box_for_whitespace: warning
    avoid_unnecessary_containers: warning
    unnecessary_string_interpolations: warning
    unnecessary_brace_in_string_interps: warning
    prefer_final_fields: warning
    prefer_final_locals: warning
    always_declare_return_types: warning
    sort_child_properties_last: warning
    use_key_in_widget_constructors: warning

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_super_parameters: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    unnecessary_string_interpolations: true
    unnecessary_brace_in_string_interps: true
    prefer_final_fields: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    no_duplicate_case_values: true
    avoid_empty_else: true
    avoid_relative_lib_imports: false
