"""add_message_source_tafsir_to_interactions_fix_feedback_type

Revision ID: 6e29af63fcb2
Revises: 86bf4aff3d18
Create Date: 2026-09-16 21:37:53.213883

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e29af63fcb2'
down_revision: str | Sequence[str] | None = '86bf4aff3d18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_mappings_id'), table_name='emotion_mappings')
    op.drop_table('emotion_mappings')
    op.add_column('interactions', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('interactions', sa.Column('tafsir', sa.Text(), nullable=True))
    op.alter_column('interactions', 'user_feedback',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="CASE WHEN user_feedback THEN 1 ELSE 0 END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactions', 'user_feedback',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('interactions', 'tafsir')
    op.drop_column('interactions', 'source')
    op.drop_column('interactions', 'message')
    op.create_table('emotion_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emotion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('example_verses', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('example_hadiths', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('emotion_mappings_pkey')),
    sa.UniqueConstraint('emotion', name=op.f('emotion_mappings_emotion_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_emotion_mappings_id'), 'emotion_mappings', ['id'], unique=False)
    # ### end Alembic commands ###
