"""Initial migration

Revision ID: 86bf4aff3d18
Revises: 
Create Date: 2026-09-16 18:25:36.868108

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86bf4aff3d18'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('example_verses', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('example_hadiths', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emotion')
    )
    op.create_index(op.f('ix_emotion_mappings_id'), 'emotion_mappings', ['id'], unique=False)
    op.create_table('hadiths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection', sa.String(length=100), nullable=False),
    sa.Column('hadith_number', sa.String(length=50), nullable=True),
    sa.Column('text_arabic', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('narrator', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('emotional_state', sa.String(length=50), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_authentic', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hadiths_collection'), 'hadiths', ['collection'], unique=False)
    op.create_index(op.f('ix_hadiths_emotional_state'), 'hadiths', ['emotional_state'], unique=False)
    op.create_index(op.f('ix_hadiths_id'), 'hadiths', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('ayah_number', sa.Integer(), nullable=False),
    sa.Column('text_arabic', sa.Text(), nullable=False),
    sa.Column('text_uthmani', sa.Text(), nullable=True),
    sa.Column('text_indopak', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('tafsir', sa.Text(), nullable=True),
    sa.Column('tafsir_source', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('emotional_state', sa.String(length=50), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verses_emotional_state'), 'verses', ['emotional_state'], unique=False)
    op.create_index(op.f('ix_verses_id'), 'verses', ['id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('detected_emotion', sa.String(length=50), nullable=True),
    sa.Column('emotion_confidence', sa.Float(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=20), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Boolean(), nullable=True),
    sa.Column('response_tier', sa.String(length=20), nullable=True),
    sa.Column('response_delayed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_created_at'), 'interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_table('delayed_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=20), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delayed_responses_id'), 'delayed_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delayed_responses_id'), table_name='delayed_responses')
    op.drop_table('delayed_responses')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_created_at'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_verses_id'), table_name='verses')
    op.drop_index(op.f('ix_verses_emotional_state'), table_name='verses')
    op.drop_table('verses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hadiths_id'), table_name='hadiths')
    op.drop_index(op.f('ix_hadiths_emotional_state'), table_name='hadiths')
    op.drop_index(op.f('ix_hadiths_collection'), table_name='hadiths')
    op.drop_table('hadiths')
    op.drop_index(op.f('ix_emotion_mappings_id'), table_name='emotion_mappings')
    op.drop_table('emotion_mappings')
    # ### end Alembic commands ###
